#pragma once

#include <Arduino.h>

const char DASHBOARD_HTML[] PROGMEM = R"HTML(
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Battery Monitor</title>
<style>
:root{color-scheme:dark;--bg:#0b1016;--panel:#151c24;--panel2:#1b2530;--text:#eef4fa;--muted:#91a1b2;--accent:#53c8ff;--good:#48d597;--bad:#ff646e;--border:#283645}
*{box-sizing:border-box} body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--bg);color:var(--text)}
.container{max-width:900px;margin:auto;padding:20px} header{margin-bottom:20px} h1{margin:0;font-size:1.7rem}.subtitle{margin-top:6px;color:var(--muted);font-size:.9rem}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.card{background:var(--panel);border:1px solid var(--border);border-radius:14px;padding:18px}.metric-actions{grid-column:1/-1;margin-top:-4px}
.metric-name{color:var(--accent);text-transform:uppercase;letter-spacing:.1em;font-size:.82rem;font-weight:700}.metric-value{margin-top:8px;font-size:2rem;font-weight:600;font-variant-numeric:tabular-nums}
.extrema{margin-top:14px;display:grid;grid-template-columns:1fr 1fr;gap:8px}.extrema div{background:var(--panel2);border-radius:8px;padding:8px 10px}.label{display:block;color:var(--muted);font-size:.7rem;text-transform:uppercase}.extrema-value{display:block;margin-top:3px;font-variant-numeric:tabular-nums}
.status-panel{margin-top:14px;display:flex;flex-wrap:wrap;gap:10px}.status{background:var(--panel);border:1px solid var(--border);border-radius:20px;padding:7px 12px;font-size:.82rem}.dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:6px;background:var(--muted)}.good .dot{background:var(--good)}.bad .dot{background:var(--bad)}
.energy-card,.sensor-card{grid-column:1/-1}.energy-summary{margin-top:14px;display:grid;grid-template-columns:1fr 1fr;gap:10px}.energy-summary div{background:var(--panel2);border-radius:10px;padding:12px}.energy-primary{display:block;margin-top:4px;font-size:2.2rem;font-weight:600;font-variant-numeric:tabular-nums}.energy-details{margin-top:10px;display:grid;grid-template-columns:1fr 1fr;gap:10px}.energy-details div{background:var(--panel2);border-radius:8px;padding:9px 12px}.energy-value{display:block;margin-top:3px;font-variant-numeric:tabular-nums}.sensor-card{padding:14px}.sensor-grid{margin-top:10px;display:grid;grid-template-columns:1fr 1fr;gap:10px}.sensor-grid>div{background:var(--panel2);border-radius:8px;padding:8px 10px}.sensor-value{display:block;margin-top:2px;font-size:1.1rem;font-weight:600;font-variant-numeric:tabular-nums}.sensor-range,.sensor-config{display:block;margin-top:4px;color:var(--muted);font-size:.72rem;font-variant-numeric:tabular-nums}.sensor-config{line-height:1.45}@media(max-width:520px){.energy-primary{font-size:1.7rem}.energy-details,.sensor-grid{grid-template-columns:1fr}}
.actions{margin-top:20px;display:flex;gap:10px;flex-wrap:wrap}button{appearance:none;border:1px solid var(--border);background:var(--panel2);color:var(--text);padding:11px 16px;border-radius:9px;font-size:.9rem;cursor:pointer}button:hover{border-color:var(--accent)}footer{margin-top:24px;color:var(--muted);font-size:.75rem}
.calibration-card{grid-column:1/-1}.firmware-card{margin-top:14px}.calibration-help,.calibration-message{margin:10px 0 0;color:var(--muted);font-size:.82rem;line-height:1.45}.calibration-message{min-height:1.3em}.calibration-grid{margin-top:14px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.calibration-grid label{color:var(--muted);font-size:.75rem}.calibration-grid input{display:block;width:100%;margin-top:5px;border:1px solid var(--border);border-radius:7px;background:var(--panel2);color:var(--text);padding:9px;font:inherit;font-variant-numeric:tabular-nums}.calibration-actions{margin-top:14px}@media(max-width:520px){.calibration-grid{grid-template-columns:1fr}}
</style>
</head>
<body>
<div class="container">
<header><h1>Battery Monitor</h1><div class="subtitle">INA228 · ESP32-C3 · <span id="firmware-version">Firmware --</span> · Live telemetry <button id="temp-unit-toggle" onclick="toggleTempUnit()" style="margin-left:8px;padding:4px 10px;font-size:.78rem">Show °F</button></div></header>
<div class="grid">
<div class="card"><div class="metric-name">Voltage</div><div class="metric-value" id="voltage">--</div><div class="extrema"><div><span class="label">Minimum</span><span class="extrema-value" id="voltage-min">--</span></div><div><span class="label">Maximum</span><span class="extrema-value" id="voltage-max">--</span></div></div></div>
<div class="card"><div class="metric-name">Current</div><div class="metric-value" id="current">--</div><div class="extrema"><div><span class="label">Minimum</span><span class="extrema-value" id="current-min">--</span></div><div><span class="label">Maximum</span><span class="extrema-value" id="current-max">--</span></div></div></div>
<div class="card"><div class="metric-name">Power</div><div class="metric-value" id="power">--</div><div class="extrema"><div><span class="label">Minimum</span><span class="extrema-value" id="power-min">--</span></div><div><span class="label">Maximum</span><span class="extrema-value" id="power-max">--</span></div></div></div>
<div class="metric-actions"><button onclick="resetExtrema()">Reset min / max</button></div>
<div class="card energy-card"><div class="metric-name">Session energy</div><div class="energy-summary"><div><span class="label">Net charge</span><span class="energy-primary" id="net-ah">--</span></div><div><span class="label">Net energy</span><span class="energy-primary" id="net-wh">--</span></div></div><div class="energy-details"><div><span class="label">Discharged</span><span class="energy-value" id="discharged-ah">--</span><span class="energy-value" id="discharged-wh">--</span></div><div><span class="label">Charged</span><span class="energy-value" id="charged-ah">--</span><span class="energy-value" id="charged-wh">--</span></div></div><div class="actions"><button onclick="resetSession()">Reset Ah / Wh</button></div></div>
<div class="card energy-card"><div class="metric-name">Battery fuel gauge</div><div class="energy-summary"><div><span class="label">State of charge</span><span class="energy-primary" id="soc-percent">--</span></div><div><span class="label">Time to empty</span><span class="energy-primary" id="soc-ttg">--</span></div></div><div class="energy-details"><div><span class="label">Deepest discharge</span><span class="energy-value" id="soc-deepest">--</span></div><div><span class="label">Full-charge cycles</span><span class="energy-value" id="soc-cycles">--</span><span class="energy-value" id="soc-avg-depth">--</span></div></div><div class="calibration-help" id="soc-message">Fuel gauge loading...</div><div class="calibration-grid"><label>Battery capacity (Ah)<input id="battery-capacity" type="number" step="0.1" min="0.1"></label><label>Charged voltage (V)<input id="battery-charged-voltage" type="number" step="0.01" min="0.1"></label></div><div class="actions calibration-actions"><button onclick="saveBattery()">Save battery profile</button><button onclick="syncBattery()">Mark as fully charged</button><button onclick="resetBatteryHistory()">Reset history</button></div></div>
<div class="card sensor-card"><div class="metric-name">Sensor details</div><div class="sensor-grid"><div><span class="label">INA228 temperature</span><span class="sensor-value" id="temperature">--</span><span class="sensor-range"><span id="temperature-min">--</span> min · <span id="temperature-max">--</span> max</span></div><div><span class="label">Shunt voltage</span><span class="sensor-value" id="shuntVoltage">--</span><span class="sensor-range"><span id="shuntVoltage-min">--</span> min · <span id="shuntVoltage-max">--</span> max</span></div></div><div class="sensor-config" id="measurement-config">INA228 configuration loading...</div></div>
<div class="card calibration-card"><div class="metric-name">Guided calibration</div><div class="calibration-help">At zero current, capture a stable shunt offset. With a stable known current applied, capture a reference and calculate gain. Saving replaces the active profile and resets min/max and Ah/Wh.</div><div class="calibration-grid"><label>Nominal shunt (mOhm)<input id="cal-resistance" type="number" step="0.001" min="0.05"></label><label>Zero offset (uV)<input id="cal-offset" type="number" step="0.01" readonly></label><label>Reference shunt sample (uV)<input id="cal-sample" type="number" step="0.01" readonly></label><label>Known reference current (A)<input id="cal-reference" type="number" step="0.001" placeholder="e.g. 5.000"></label><label>Current gain<input id="cal-gain" type="number" step="0.000001" min="0.5" max="1.5"></label></div><div class="calibration-help" id="calibration-samples">Waiting for shunt samples...</div><div class="actions calibration-actions"><button onclick="usePrototypePreset()">Use 15 mOhm prototype</button><button onclick="useFinalShuntPreset()">Stage 0.5 mOhm final shunt</button><button onclick="showKelvinChecklist()">Kelvin wiring checklist</button><button onclick="captureZero()">1. Capture zero</button><button onclick="captureReference()">2. Capture reference</button><button onclick="calculateGain()">3. Calculate gain</button><button onclick="saveCalibration()">Save calibration</button><button onclick="resetCalibration()">Restore default</button></div><div class="calibration-message" id="calibration-message">Calibration loading...</div></div>
<div class="card calibration-card"><div class="metric-name">Device alarms</div><div class="calibration-help">Stored in the monitor and evaluated even when no phone is connected. All thresholds are disabled by default.</div><div class="calibration-grid"><label>Enabled flags (1 low V, 2 high V, 4 current, 8 temperature, 16 sensor)<input id="alarm-flags" type="number" min="0" max="31"></label><label>Low voltage (V)<input id="alarm-low" type="number" step="0.001"></label><label>High voltage (V)<input id="alarm-high" type="number" step="0.001"></label><label>Absolute current (A)<input id="alarm-current" type="number" step="0.001"></label><label>Temperature (<span id="alarm-temp-unit">°C</span>)<input id="alarm-temperature" type="number" step="0.1"></label></div><div class="actions calibration-actions"><button onclick="saveAlarms()">Save device alarms</button></div><div class="calibration-message" id="alarm-message">Alarm configuration loading...</div></div>
<div class="card calibration-card"><div class="metric-name">Wi-Fi station &amp; mDNS</div><div class="calibration-help">The local <strong>BatteryMonitor</strong> AP always remains available as a recovery path. Save your home-network credentials to join it in parallel; when connected, open <strong>http://battery-monitor.local/</strong> from the same network. The stored password is never shown here. Enter it each time you save (leave it blank only for an open network).</div><div class="calibration-grid"><label>Home Wi-Fi name (SSID)<input id="wifi-ssid" type="text" maxlength="32" autocomplete="off"></label><label>Home Wi-Fi password<input id="wifi-password" type="password" maxlength="63" autocomplete="new-password"></label></div><div class="actions calibration-actions"><button onclick="saveWifi()">Save &amp; connect</button><button onclick="clearWifi()">Forget home Wi-Fi</button></div><div class="calibration-message" id="wifi-message">Home Wi-Fi not configured. AP recovery is active.</div></div>
<div class="card calibration-card"><div class="metric-name">MQTT / Home Assistant</div><div class="calibration-help">Publishes live telemetry to an MQTT broker with Home Assistant auto-discovery; entities appear automatically once the broker connects. Requires the home Wi-Fi station above. The stored password is never shown here. Enter it each time you save (leave blank only if the broker needs no authentication).</div><div class="calibration-grid"><label>Broker host<input id="mqtt-host" type="text" maxlength="64" autocomplete="off"></label><label>Broker port<input id="mqtt-port" type="number" min="1" max="65535" step="1"></label><label>Username (optional)<input id="mqtt-username" type="text" maxlength="32" autocomplete="off"></label><label>Password (optional)<input id="mqtt-password" type="password" maxlength="64" autocomplete="new-password"></label></div><label style="display:block;margin-top:10px;color:var(--muted);font-size:.82rem"><input id="mqtt-enabled" type="checkbox" style="width:auto;margin-right:6px;vertical-align:middle">Enable MQTT publishing</label><div class="actions calibration-actions"><button onclick="saveMqtt()">Save MQTT settings</button></div><div class="calibration-message" id="mqtt-message">MQTT not configured.</div></div>
<div class="card calibration-card"><div class="metric-name">Load protection relay</div><div class="calibration-help">Disconnects a relay/SSR-switched load once voltage or state of charge drops below the thresholds below. Disabled by default and has no effect until enabled here. Once tripped, the load stays disconnected until you tap Reconnect below &mdash; it never reconnects on its own, so it cannot chatter if a reading hovers right at the threshold under load.</div><div class="calibration-grid"><label>Low voltage cutoff (V)<input id="protection-voltage" type="number" step="0.01" min="0"></label><label>Low state of charge cutoff (%)<input id="protection-soc" type="number" step="0.1" min="0" max="100"></label></div><label style="display:block;margin-top:10px;color:var(--muted);font-size:.82rem"><input id="protection-enabled" type="checkbox" style="width:auto;margin-right:6px;vertical-align:middle">Enable load protection</label><div class="actions calibration-actions"><button onclick="saveProtection()">Save protection settings</button><button onclick="reconnectLoad()">Reconnect load</button></div><div class="calibration-help">Bench-test the relay wiring directly, regardless of the settings above or whether protection is enabled:</div><div class="actions calibration-actions"><button onclick="testConnectRelay()">Test: force connect</button><button onclick="testDisconnectRelay()">Test: force disconnect</button></div><div class="calibration-message" id="protection-message">Load protection disabled.</div></div>
</div>
<div class="status-panel">
<div class="status" id="sensor-status"><span class="dot"></span>INA228</div>
<div class="status" id="ble-status"><span class="dot"></span>BLE</div>
<div class="status" id="wifi-status"><span class="dot"></span>Wi-Fi AP</div>
<div class="status" id="i2c-status"><span class="dot"></span>I2C</div>
<div class="status" id="display-status"><span class="dot"></span>Display</div>
</div>
<div class="actions"><button id="display-toggle" onclick="toggleDisplay()">Turn display off</button></div>
<div class="card firmware-card"><div class="metric-name">Firmware update</div><div class="calibration-help">Checking for updates needs this device (not the monitor) to have internet access &mdash; it won't work while connected only to the BatteryMonitor recovery AP. Choose a release .bin from this phone or computer to install. The selected image is checked for its embedded version before upload. Keep this page open until the monitor confirms the update and reboots. Do not remove power during the upload.</div><div class="actions calibration-actions"><button onclick="checkFirmwareUpdate()">Check for updates</button></div><div class="calibration-message" id="firmware-update-message"></div><div class="actions calibration-actions" id="firmware-download-wrap"></div><div class="actions calibration-actions"><input id="firmware-file" type="file" accept=".bin,application/octet-stream" onchange="inspectFirmwareFile()"><button onclick="uploadFirmware()">Upload firmware</button></div><div class="calibration-message" id="firmware-current">Current firmware: --</div><div class="calibration-message" id="firmware-selected">Selected firmware: no file selected</div><div class="calibration-message" id="firmware-message"></div></div>
<footer><span id="uptime">Uptime --</span> · <span id="clients">0 Wi-Fi clients</span> · <span id="reset-reason">Last reset: --</span></footer>
</div>
<script>
const num=v=>typeof v==='number'&&Number.isFinite(v);
const fmtV=v=>num(v)?v.toFixed(3)+' V':'--';
const fmtI=v=>!num(v)?'--':Math.abs(v)<1?(v*1000).toFixed(3)+' mA':v.toFixed(3)+' A';
const fmtP=v=>!num(v)?'--':Math.abs(v)<1?(v*1000).toFixed(3)+' mW':v.toFixed(2)+' W';
let tempUnit=localStorage.getItem('tempUnit')==='F'?'F':'C';
document.getElementById('temp-unit-toggle').textContent='Show °'+(tempUnit==='C'?'F':'C');
document.getElementById('alarm-temp-unit').textContent='°'+tempUnit;
function toDisplayTemp(c){return tempUnit==='F'?c*9/5+32:c}
function toCelsius(v){return tempUnit==='F'?(v-32)*5/9:v}
function toggleTempUnit(){tempUnit=tempUnit==='C'?'F':'C';localStorage.setItem('tempUnit',tempUnit);document.getElementById('temp-unit-toggle').textContent='Show °'+(tempUnit==='C'?'F':'C');document.getElementById('alarm-temp-unit').textContent='°'+tempUnit;if(latestTelemetry)applyTelemetry(latestTelemetry)}
const fmtT=v=>num(v)?toDisplayTemp(v).toFixed(1)+' °'+tempUnit:'--';
const fmtS=v=>num(v)?(v*1000).toFixed(4)+' mV':'--';
const fmtAh=v=>!num(v)?'--':Math.abs(v)<1?(v*1000).toFixed(3)+' mAh':v.toFixed(4)+' Ah';
const fmtWh=v=>!num(v)?'--':Math.abs(v)<1?(v*1000).toFixed(3)+' mWh':v.toFixed(4)+' Wh';
const fmtR=v=>num(v)?(v*1000).toFixed(3)+' mOhm':'--';
let latestTelemetry=null;let calibrationDirty=false;let finalShuntPreset=false;let calibrationSamples=[];let refreshInFlight=false;let commandInFlight=false;let refreshTimer=0;const REFRESH_INTERVAL_MS=500;const CALIBRATION_MAX_SAMPLE_AGE_MS=1500;
function metric(name,data,fmt){document.getElementById(name).textContent=fmt(data.value);document.getElementById(name+'-min').textContent=fmt(data.min);document.getElementById(name+'-max').textContent=fmt(data.max)}
function energy(data){document.getElementById('net-ah').textContent=fmtAh(data.netAh);document.getElementById('net-wh').textContent=fmtWh(data.netWh);document.getElementById('discharged-ah').textContent=fmtAh(data.dischargedAh);document.getElementById('discharged-wh').textContent=fmtWh(data.dischargedWh);document.getElementById('charged-ah').textContent=fmtAh(data.chargedAh);document.getElementById('charged-wh').textContent=fmtWh(data.chargedWh)}
function measurement(data){const e=document.getElementById('measurement-config');if(!data||!data.calibration){e.textContent='Measurement configuration unavailable';return}const c=data.calibration;const state=data.ina228Configured?'INA228 configured':data.ina228ReadbackValid?'INA228 configuration mismatch':'INA228 readback unavailable';const range=data.ina228ReadbackValid?(data.wideShuntRange?'wide +/-163.84 mV':'narrow +/-40.96 mV'):'range unavailable';const timing=data.ina228ReadbackValid?(data.averages+'x average | '+data.conversionTimeUs+' us conversion'):'timing unavailable';const source=c.stored?'stored calibration':'default calibration';e.textContent=state+' | '+range+' | '+timing+' | '+fmtR(c.shuntResistanceOhms)+' | offset '+c.shuntOffsetMicrovolts.toFixed(2)+' uV | gain '+c.currentGain.toFixed(6)+' ('+source+')';document.getElementById('calibration-message').textContent='Active profile: '+data.status;if(!calibrationDirty){document.getElementById('cal-resistance').value=(c.shuntResistanceOhms*1000).toFixed(6);document.getElementById('cal-offset').value=c.shuntOffsetMicrovolts.toFixed(2);document.getElementById('cal-gain').value=c.currentGain.toFixed(6)}}
function calibrationMessage(text){document.getElementById('calibration-message').textContent=text}
function alarms(data){if(!data)return;document.getElementById('alarm-message').textContent=data.activeFlags?'ACTIVE alarm flags: '+data.activeFlags:'No device alarms active';if(document.activeElement&&document.activeElement.id&&document.activeElement.id.startsWith('alarm-'))return;document.getElementById('alarm-flags').value=data.enabledFlags;document.getElementById('alarm-low').value=data.lowVoltage.toFixed(3);document.getElementById('alarm-high').value=data.highVoltage.toFixed(3);document.getElementById('alarm-current').value=data.maxCurrent.toFixed(3);document.getElementById('alarm-temperature').value=toDisplayTemp(data.maxTemperature).toFixed(1)}
function battery(data){if(!data)return;document.getElementById('soc-percent').textContent=data.known?data.percent.toFixed(1)+'%':'--';document.getElementById('soc-ttg').textContent=data.hasTimeToEmpty?uptime(data.timeToEmptySeconds):(data.known?'Not discharging':'--');document.getElementById('soc-deepest').textContent=data.deepestDischargePercent.toFixed(1)+'%';document.getElementById('soc-cycles').textContent=data.fullChargeCycles+(data.fullChargeCycles===1?' cycle':' cycles');document.getElementById('soc-avg-depth').textContent=data.fullChargeCycles>0?('avg '+data.averageDischargeDepthPercent.toFixed(1)+'% depth'):'';document.getElementById('soc-message').textContent=data.known?'Remaining '+data.remainingAh.toFixed(3)+' of '+data.capacityAh.toFixed(3)+' Ah.':'Not yet synced. Fully charge the battery (voltage at or above the charged threshold with a low, tapering current) or tap "Mark as fully charged" once you know it is full.';if(document.activeElement&&document.activeElement.id&&document.activeElement.id.startsWith('battery-'))return;document.getElementById('battery-capacity').value=data.capacityAh.toFixed(3);document.getElementById('battery-charged-voltage').value=data.chargedVoltage.toFixed(3)}
function wifi(data){if(!data)return;const ssid=document.getElementById('wifi-ssid');if(document.activeElement!==ssid)ssid.value=data.stationConfigured?(data.stationSsid||''):'';const message=document.getElementById('wifi-message');if(!data.stationConfigured){message.textContent='Home Wi-Fi not configured. AP recovery: '+(data.accessPointSsid||'BatteryMonitor')+' at '+(data.accessPointIp||'192.168.4.1');return}if(data.stationConnected){const address=data.mdnsHostname?'http://'+data.mdnsHostname+'.local/':data.stationIp?'http://'+data.stationIp+'/':'connected';message.textContent='Connected to '+data.stationSsid+' at '+(data.stationIp||'unknown IP')+(data.mdnsHostname?' · '+address:'');return}message.textContent='Connecting to '+data.stationSsid+'... AP recovery remains available at '+(data.accessPointIp||'192.168.4.1')}
function mqtt(data){if(!data)return;const editing=document.activeElement&&document.activeElement.id&&document.activeElement.id.startsWith('mqtt-');const message=document.getElementById('mqtt-message');if(!editing){document.getElementById('mqtt-host').value=data.host||'';document.getElementById('mqtt-port').value=data.port||1883;document.getElementById('mqtt-username').value=data.username||'';document.getElementById('mqtt-enabled').checked=!!data.enabled}if(!data.enabled){message.textContent='MQTT publishing disabled.';return}message.textContent=data.connected?'Connected to '+data.host+':'+data.port+'.':'Configured for '+data.host+':'+data.port+', not yet connected.'}
function protection(data){if(!data)return;const editing=document.activeElement&&document.activeElement.id&&document.activeElement.id.startsWith('protection-');const message=document.getElementById('protection-message');if(!editing){document.getElementById('protection-voltage').value=data.lowVoltageThreshold.toFixed(3);document.getElementById('protection-soc').value=data.lowSocPercentThreshold.toFixed(1);document.getElementById('protection-enabled').checked=!!data.enabled}const reasons=[];if(data.tripFlags&1)reasons.push('low voltage');if(data.tripFlags&2)reasons.push('low SoC');if(data.tripFlags&4)reasons.push('manual test');if(!data.relayEngaged){message.textContent='Load DISCONNECTED'+(reasons.length?' ('+reasons.join(' + ')+')':'')+'. '+(data.breachFlags!==0?'Condition still active; reconnect will be rejected.':'Condition clear; safe to reconnect.');return}message.textContent=data.enabled?'Load connected. Monitoring for low voltage/SoC.':'Load protection disabled; relay stays connected.'}
function updateCalibrationSamples(t){if(!t||!t.sensorOK||!num(t.sampleAgeMs)||t.sampleAgeMs>CALIBRATION_MAX_SAMPLE_AGE_MS||!num(t.shuntVoltage.value))return;const value=t.shuntVoltage.value*1e6;if(calibrationSamples.length&&calibrationSamples[calibrationSamples.length-1].sequence===t.sampleSequence)return;calibrationSamples.push({sequence:t.sampleSequence,value});if(calibrationSamples.length>8)calibrationSamples.shift();const values=calibrationSamples.map(x=>x.value),avg=values.reduce((a,b)=>a+b,0)/values.length,min=Math.min(...values),max=Math.max(...values),stable=values.length>=4&&max-min<=Math.abs(avg)*.02+.1;document.getElementById('calibration-samples').textContent=values.length+'/8 samples | '+avg.toFixed(3)+' uV avg | '+(max-min).toFixed(3)+' uV spread | '+(stable?'stable':'settling')}
function currentShuntMicrovolts(){if(calibrationSamples.length<4){calibrationMessage('Wait for four stable shunt samples before capturing.');return null}const values=calibrationSamples.map(x=>x.value),avg=values.reduce((a,b)=>a+b,0)/values.length,min=Math.min(...values),max=Math.max(...values);if(max-min>Math.abs(avg)*.02+.1){calibrationMessage('Shunt samples are still changing. Let the reading settle.');return null}return avg}
function captureZero(){const value=currentShuntMicrovolts();if(value===null)return;document.getElementById('cal-offset').value=value.toFixed(3);calibrationDirty=true;calibrationMessage('Stable zero average captured. Confirm there is no current before continuing.')}
function captureReference(){const value=currentShuntMicrovolts();if(value===null)return;document.getElementById('cal-sample').value=value.toFixed(3);calibrationDirty=true;calibrationMessage('Stable reference average captured. Enter the trusted current, then calculate gain.')}
function usePrototypePreset(){document.getElementById('cal-resistance').value='15.000';document.getElementById('cal-offset').value='0.000';document.getElementById('cal-gain').value='1.000000';finalShuntPreset=false;calibrationDirty=true;calibrationMessage('15 mOhm prototype preset staged. Save calibration to apply it.')}
function useFinalShuntPreset(){document.getElementById('cal-resistance').value='0.500';document.getElementById('cal-offset').value='0.000';document.getElementById('cal-gain').value='1.000000';finalShuntPreset=true;calibrationDirty=true;calibrationMessage('0.5 mOhm / 100 A / 50 mV final-shunt preset staged. Verify wiring before saving.')}
function showKelvinChecklist(){alert('Final Kelvin shunt checklist:\n\n1. Put the shunt in the battery negative path.\n2. VIN+ goes to the source-side Kelvin terminal.\n3. VIN- goes to the load-side Kelvin terminal.\n4. Keep sense wires twisted and away from high-current cables.\n5. Capture zero at no load, then verify with a small known load.\n\nThis orientation reports discharge current as positive.')}
function calculateGain(){const r=Number(document.getElementById('cal-resistance').value)*1e-3;const offset=Number(document.getElementById('cal-offset').value)*1e-6;const sample=Number(document.getElementById('cal-sample').value)*1e-6;const reference=Number(document.getElementById('cal-reference').value);const observed=(sample-offset)/r;if(!Number.isFinite(observed)||!Number.isFinite(reference)||Math.abs(observed)<1e-9||Math.abs(reference)<1e-9||Math.sign(observed)!==Math.sign(reference)){calibrationMessage('Use a non-zero reference with the same current direction as the captured sample.');return}const gain=reference/observed;if(gain<0.5||gain>1.5){calibrationMessage('Calculated gain is outside the permitted 0.5 to 1.5 range. Check wiring and reference current.');return}document.getElementById('cal-gain').value=gain.toFixed(6);calibrationDirty=true;calibrationMessage('Gain calculated. Review all values, then save calibration.')}
async function postApi(path){if(commandInFlight)return false;commandInFlight=true;try{const response=await fetch(path,{method:'POST',cache:'no-store'});return response.ok}catch(e){return false}finally{commandInFlight=false}}
async function saveCalibration(){const r=Number(document.getElementById('cal-resistance').value)*1e-3;const offset=Number(document.getElementById('cal-offset').value)*1e-6;const gain=Number(document.getElementById('cal-gain').value);if(!Number.isFinite(r)||!Number.isFinite(offset)||!Number.isFinite(gain)){calibrationMessage('Enter valid calibration values before saving.');return}if(finalShuntPreset&&!confirm('Apply the 0.500 mOhm final-shunt calibration? This resets session values. Continue only after its Kelvin wiring is verified.'))return;const q=new URLSearchParams({resistance:String(r),offset:String(offset),gain:String(gain)});if(!await postApi('/api/calibration/save?'+q)){calibrationMessage('Calibration was not accepted. Wait for any pending command, then check the values.');return}calibrationDirty=false;finalShuntPreset=false;calibrationMessage('Saving calibration...');scheduleRefresh(150)}
async function resetCalibration(){if(!confirm('Restore the compile-time default calibration? This resets min/max and Ah/Wh.'))return;if(!await postApi('/api/calibration/reset')){calibrationMessage('Unable to restore the default calibration.');return}calibrationDirty=false;calibrationMessage('Restoring default calibration...');scheduleRefresh(150)}
async function saveAlarms(){const flags=Number(document.getElementById('alarm-flags').value),low=Number(document.getElementById('alarm-low').value),high=Number(document.getElementById('alarm-high').value),current=Number(document.getElementById('alarm-current').value),temperatureInput=Number(document.getElementById('alarm-temperature').value);if(![flags,low,high,current,temperatureInput].every(Number.isFinite)){document.getElementById('alarm-message').textContent='Enter valid alarm values.';return}const temperature=toCelsius(temperatureInput);const q=new URLSearchParams({flags:String(flags),low:String(low),high:String(high),current:String(current),temperature:String(temperature)});if(!await postApi('/api/alarms/save?'+q)){document.getElementById('alarm-message').textContent='Alarm settings were rejected.';return}document.getElementById('alarm-message').textContent='Saving device alarms...';scheduleRefresh(150)}
async function saveWifi(){const ssid=document.getElementById('wifi-ssid').value.trim(),password=document.getElementById('wifi-password').value,message=document.getElementById('wifi-message');if(!ssid){message.textContent='Enter the home Wi-Fi name.';return}if(password&&password.length<8){message.textContent='Wi-Fi passwords must be at least 8 characters (or leave blank only for an open network).';return}try{const r=await fetch('/api/wifi/save',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({ssid,password})});const d=await r.json();message.textContent=r.ok?'Saved. Connecting while the BatteryMonitor AP remains available.':(d.error||'Wi-Fi settings were rejected.');if(r.ok)document.getElementById('wifi-password').value='';scheduleRefresh(150)}catch(e){message.textContent='Wi-Fi settings request failed. Stay connected to the BatteryMonitor AP and try again.'}}
async function saveBattery(){const capacity=Number(document.getElementById('battery-capacity').value),chargedVoltage=Number(document.getElementById('battery-charged-voltage').value),message=document.getElementById('soc-message');if(!Number.isFinite(capacity)||capacity<=0||!Number.isFinite(chargedVoltage)||chargedVoltage<=0){message.textContent='Enter a valid capacity and charged voltage.';return}const q=new URLSearchParams({capacity:String(capacity),chargedVoltage:String(chargedVoltage)});if(!await postApi('/api/battery/save?'+q)){message.textContent='Battery profile was rejected.';return}message.textContent='Saving battery profile...';scheduleRefresh(150)}
async function syncBattery(){if(!confirm('Mark the battery as fully charged now? This resets the fuel gauge to 100%.'))return;const message=document.getElementById('soc-message');if(!await postApi('/api/battery/sync')){message.textContent='Unable to sync the fuel gauge.';return}message.textContent='Fuel gauge synced to 100%.';scheduleRefresh(150)}
async function resetBatteryHistory(){if(!confirm('Reset deepest discharge, cycle count and average depth? Do this after replacing the physical battery. Current charge level is not affected.'))return;const message=document.getElementById('soc-message');if(!await postApi('/api/battery/reset-history')){message.textContent='Unable to reset battery history.';return}message.textContent='Battery history reset.';scheduleRefresh(150)}
async function clearWifi(){if(!confirm('Forget the stored home Wi-Fi credentials? The BatteryMonitor AP stays available.'))return;const message=document.getElementById('wifi-message');try{const r=await fetch('/api/wifi/clear',{method:'POST'});const d=await r.json();message.textContent=r.ok?'Home Wi-Fi forgotten. AP recovery remains active.':(d.error||'Unable to clear Wi-Fi settings.');if(r.ok){document.getElementById('wifi-ssid').value='';document.getElementById('wifi-password').value=''}scheduleRefresh(150)}catch(e){message.textContent='Unable to clear Wi-Fi settings.'}}
async function saveMqtt(){const host=document.getElementById('mqtt-host').value.trim(),port=document.getElementById('mqtt-port').value,username=document.getElementById('mqtt-username').value,password=document.getElementById('mqtt-password').value,enabled=document.getElementById('mqtt-enabled').checked,message=document.getElementById('mqtt-message');if(enabled&&!host){message.textContent='Enter the broker host to enable MQTT.';return}try{const body=new URLSearchParams({host,port:port||'1883',username,password});if(enabled)body.set('enabled','1');const r=await fetch('/api/mqtt/save',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const d=await r.json();message.textContent=r.ok?'Saved.':(d.error||'MQTT settings were rejected.');if(r.ok)document.getElementById('mqtt-password').value='';scheduleRefresh(150)}catch(e){message.textContent='MQTT settings request failed.'}}
async function saveProtection(){const lowVoltage=Number(document.getElementById('protection-voltage').value),lowSocPercent=Number(document.getElementById('protection-soc').value),enabled=document.getElementById('protection-enabled').checked,message=document.getElementById('protection-message');if(!Number.isFinite(lowVoltage)||!Number.isFinite(lowSocPercent)){message.textContent='Enter valid voltage and state-of-charge thresholds.';return}if(enabled&&!confirm('Enable load protection? The load will disconnect automatically once voltage drops below '+lowVoltage+' V or SoC drops below '+lowSocPercent+'%, and will stay disconnected until you tap Reconnect.'))return;const q=new URLSearchParams({lowVoltage:String(lowVoltage),lowSocPercent:String(lowSocPercent)});if(enabled)q.set('enabled','1');if(!await postApi('/api/protection/save?'+q)){message.textContent='Protection settings were rejected.';return}message.textContent='Saving protection settings...';scheduleRefresh(150)}
async function reconnectLoad(){const message=document.getElementById('protection-message');if(!confirm('Reconnect the load now? This is rejected if voltage or SoC is still below the configured threshold.'))return;if(!await postApi('/api/protection/reconnect')){message.textContent='Unable to request reconnect.';return}message.textContent='Requesting reconnect...';scheduleRefresh(150)}
async function testDisconnectRelay(){const message=document.getElementById('protection-message');if(!confirm('Bench test: force the relay OPEN (load disconnected) right now, bypassing all thresholds?'))return;if(!await postApi('/api/protection/test-disconnect')){message.textContent='Unable to force disconnect.';return}message.textContent='Forcing relay open (test)...';scheduleRefresh(150)}
async function testConnectRelay(){const message=document.getElementById('protection-message');if(!confirm('Bench test: force the relay CLOSED (load connected) right now, bypassing all thresholds?'))return;if(!await postApi('/api/protection/test-connect')){message.textContent='Unable to force connect.';return}message.textContent='Forcing relay closed (test)...';scheduleRefresh(150)}
function firmwareVersionInImage(bytes){const marker=[66,77,70,87,58];for(let i=0;i<=bytes.length-marker.length;i++){let found=true;for(let j=0;j<marker.length;j++)if(bytes[i+j]!==marker[j]){found=false;break}if(!found)continue;let version='';for(let j=i+marker.length;j<bytes.length&&j<i+marker.length+32;j++){const c=bytes[j];if(c===0)break;if((c>=48&&c<=57)||c===46||c===45||c===43||c===95||c>=65&&c<=90||c>=97&&c<=122)version+=String.fromCharCode(c);else break}if(version)return version}return null}
async function inspectFirmwareFile(){const file=document.getElementById('firmware-file').files[0],selected=document.getElementById('firmware-selected'),message=document.getElementById('firmware-message');message.textContent='';if(!file){selected.textContent='Selected firmware: no file selected';return}if(!file.name.toLowerCase().endsWith('.bin')){selected.textContent='Selected firmware: not a .bin file';return}selected.textContent='Selected firmware: checking '+file.name+'...';try{const version=firmwareVersionInImage(new Uint8Array(await file.arrayBuffer()));selected.textContent=version?'Selected firmware: v'+version+' ('+file.name+')':'Selected firmware: version marker not found ('+file.name+')'}catch(e){selected.textContent='Selected firmware: unable to inspect '+file.name}}
async function uploadFirmware(){const file=document.getElementById('firmware-file').files[0],message=document.getElementById('firmware-message');if(!file||!file.name.endsWith('.bin')){message.textContent='Select a firmware .bin file first.';return}if(!confirm('Upload '+file.name+'? Do not remove power while the monitor restarts.'))return;const form=new FormData();form.append('firmware',file);message.textContent='Uploading firmware...';try{const response=await fetch('/api/firmware',{method:'POST',body:form});const data=await response.json();message.textContent=response.ok?'Firmware accepted. The monitor is restarting...':(data.error||'Firmware update failed.')}catch(e){message.textContent='Upload connection lost. Wait for the monitor to reboot, then check its version.'}}
function compareVersions(a,b){const pa=a.split('.').map(Number),pb=b.split('.').map(Number);for(let i=0;i<Math.max(pa.length,pb.length);i++){const x=pa[i]||0,y=pb[i]||0;if(x!==y)return x-y}return 0}
async function checkFirmwareUpdate(){
  const message=document.getElementById('firmware-update-message');
  const linkWrap=document.getElementById('firmware-download-wrap');
  linkWrap.innerHTML='';
  const installed=latestTelemetry&&latestTelemetry.firmwareVersion;
  if(!installed){message.textContent='Waiting for the monitor firmware version before checking.';return}
  message.textContent='Checking github.com for a newer release...';
  try{
    const r=await fetch('https://api.github.com/repos/duceppemo/battery_current_monitor/releases/latest',{headers:{'Accept':'application/vnd.github+json'}});
    if(!r.ok)throw new Error('GitHub returned HTTP '+r.status);
    const release=await r.json();
    const latest=(release.tag_name||'').replace(/^v/,'');
    if(!latest){message.textContent='No published release found.';return}
    const cmp=compareVersions(latest,installed);
    if(cmp<=0){message.textContent=cmp<0?('Installed firmware v'+installed+' is newer than the latest published v'+latest+'.'):('Firmware v'+installed+' is up to date.');return}
    const asset=(release.assets||[]).find(a=>a.name&&a.name.toLowerCase().endsWith('.bin')&&!a.name.toLowerCase().includes('factory'));
    if(!asset){message.textContent='Update v'+latest+' is published but has no installable OTA .bin asset yet.';return}
    message.textContent='Update available: v'+installed+' → v'+latest+'.';
    const link=document.createElement('a');
    link.href=asset.browser_download_url;
    link.download=asset.name;
    link.textContent='Download '+asset.name;
    linkWrap.appendChild(link);
  }catch(e){
    message.textContent='Unable to check for updates (this device needs its own internet access, separate from the monitor): '+e.message;
  }
}
function status(id,ok,text){const e=document.getElementById(id);e.classList.remove('good','bad');e.classList.add(ok?'good':'bad');e.innerHTML='<span class="dot"></span>'+text}
function uptime(s){s=Math.floor(s);const d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60);return d?d+'d '+h+'h':h?h+'h '+m+'m':m+'m'}
function applyTelemetry(d){latestTelemetry=d;document.getElementById('firmware-version').textContent='Firmware v'+(d.firmwareVersion||'--');document.getElementById('firmware-current').textContent='Current firmware: v'+(d.firmwareVersion||'--');updateCalibrationSamples(d);const fresh=num(d.sampleAgeMs)&&d.sampleAgeMs<=CALIBRATION_MAX_SAMPLE_AGE_MS;const healthy=d.sensorOK&&fresh;metric('voltage',d.voltage,fmtV);metric('current',d.current,fmtI);metric('power',d.power,fmtP);metric('temperature',d.temperature,fmtT);metric('shuntVoltage',d.shuntVoltage,fmtS);energy(d.energy);battery(d.battery);measurement(d.measurement);alarms(d.alarms);wifi(d.wifi);mqtt(d.mqtt);protection(d.protection);status('sensor-status',healthy,healthy?'INA228 OK':fresh?'INA228 error':'Telemetry stale');status('ble-status',d.bleConnected||d.bleAdvertising,d.bleConnected?'BLE connected':d.bleAdvertising?'BLE advertising':'BLE unavailable');status('wifi-status',d.accessPointReady||(d.wifi&&d.wifi.stationConnected),'Wi-Fi '+(d.wifi&&d.wifi.stationConnected?'station connected':d.accessPointReady?'AP fallback ready':'unavailable'));status('i2c-status',d.sensorOK,'Current sample: '+(d.sensorOK?'complete':'incomplete')+'; total incomplete: '+d.failedSamples);status('display-status',d.displayOn,d.displayOn?'Display on':'Display off');document.getElementById('display-toggle').textContent=d.displayOn?'Turn display off':'Turn display on';document.getElementById('uptime').textContent='Uptime '+uptime(d.uptimeSeconds);document.getElementById('clients').textContent=d.wifiClients+(d.wifiClients===1?' Wi-Fi client':' Wi-Fi clients');document.getElementById('reset-reason').textContent='Last reset: '+d.resetReason}
// The dashboard prefers a push WebSocket (see WebDashboard::broadcastTelemetryIfDue)
// over polling /api/telemetry; polling only runs as a fallback while the
// socket is down, so it never fights the socket for the same DOM updates.
let ws=null,wsConnected=false,wsReconnectTimer=0;
function scheduleRefresh(delay=REFRESH_INTERVAL_MS){if(wsConnected)return;clearTimeout(refreshTimer);refreshTimer=setTimeout(pollTelemetry,delay)}
async function pollTelemetry(){if(wsConnected||refreshInFlight)return;refreshInFlight=true;try{const r=await fetch('/api/telemetry',{cache:'no-store'});if(!r.ok)throw Error();applyTelemetry(await r.json())}catch(e){latestTelemetry=null;status('sensor-status',false,'Connection lost')}finally{refreshInFlight=false;scheduleRefresh()}}
function connectWebSocket(){try{ws=new WebSocket('ws://'+location.hostname+':81/')}catch(e){scheduleWsReconnect();return}ws.onopen=()=>{wsConnected=true;clearTimeout(refreshTimer)};ws.onmessage=(event)=>{try{applyTelemetry(JSON.parse(event.data))}catch(e){}};ws.onclose=()=>{wsConnected=false;pollTelemetry();scheduleWsReconnect()};ws.onerror=()=>{try{ws.close()}catch(e){}}}
function scheduleWsReconnect(){clearTimeout(wsReconnectTimer);wsReconnectTimer=setTimeout(connectWebSocket,3000)}
async function resetExtrema(){if(await postApi('/api/reset-extrema'))scheduleRefresh(100)}
async function resetSession(){if(await postApi('/api/reset-session'))scheduleRefresh(100)}
async function toggleDisplay(){if(await postApi('/api/toggle-display'))scheduleRefresh(100)}
for(const id of ['cal-resistance','cal-reference','cal-gain'])document.getElementById(id).addEventListener('input',()=>{calibrationDirty=true});
pollTelemetry();
connectWebSocket();
</script>
</body>
</html>
)HTML";
