#pragma once

#include <Arduino.h>

const char DASHBOARD_HTML[] PROGMEM = R"HTML(
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>Battery Monitor</title>
<style>
:root{color-scheme:dark;--bg:#0b1016;--panel:#151c24;--panel2:#1b2530;--text:#eef4fa;--muted:#91a1b2;--accent:#53c8ff;--good:#48d597;--bad:#ff646e;--border:#283645}
*{box-sizing:border-box} body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--bg);color:var(--text)}
.container{max-width:900px;margin:auto;padding:20px} header{margin-bottom:20px} h1{margin:0;font-size:1.7rem}.subtitle{margin-top:6px;color:var(--muted);font-size:.9rem}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px}.card{background:var(--panel);border:1px solid var(--border);border-radius:14px;padding:18px}
.metric-name{color:var(--muted);text-transform:uppercase;letter-spacing:.08em;font-size:.75rem}.metric-value{margin-top:8px;font-size:2rem;font-weight:600;font-variant-numeric:tabular-nums}
.extrema{margin-top:14px;display:grid;grid-template-columns:1fr 1fr;gap:8px}.extrema div{background:var(--panel2);border-radius:8px;padding:8px 10px}.label{display:block;color:var(--muted);font-size:.7rem;text-transform:uppercase}.extrema-value{display:block;margin-top:3px;font-variant-numeric:tabular-nums}
.status-panel{margin-top:14px;display:flex;flex-wrap:wrap;gap:10px}.status{background:var(--panel);border:1px solid var(--border);border-radius:20px;padding:7px 12px;font-size:.82rem}.dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:6px;background:var(--muted)}.good .dot{background:var(--good)}.bad .dot{background:var(--bad)}
.energy-card,.sensor-card{grid-column:1/-1}.energy-summary{margin-top:14px;display:grid;grid-template-columns:1fr 1fr;gap:10px}.energy-summary div{background:var(--panel2);border-radius:10px;padding:12px}.energy-primary{display:block;margin-top:4px;font-size:2.2rem;font-weight:600;font-variant-numeric:tabular-nums}.energy-details{margin-top:10px;display:grid;grid-template-columns:1fr 1fr;gap:10px}.energy-details div{background:var(--panel2);border-radius:8px;padding:9px 12px}.energy-value{display:block;margin-top:3px;font-variant-numeric:tabular-nums}.sensor-card{padding:14px}.sensor-grid{margin-top:10px;display:grid;grid-template-columns:1fr 1fr;gap:10px}.sensor-grid>div{background:var(--panel2);border-radius:8px;padding:8px 10px}.sensor-value{display:block;margin-top:2px;font-size:1.1rem;font-weight:600;font-variant-numeric:tabular-nums}.sensor-range,.sensor-config{display:block;margin-top:4px;color:var(--muted);font-size:.72rem;font-variant-numeric:tabular-nums}.sensor-config{line-height:1.45}@media(max-width:520px){.energy-primary{font-size:1.7rem}.energy-details,.sensor-grid{grid-template-columns:1fr}}
.actions{margin-top:20px;display:flex;gap:10px;flex-wrap:wrap}button{appearance:none;border:1px solid var(--border);background:var(--panel2);color:var(--text);padding:11px 16px;border-radius:9px;font-size:.9rem;cursor:pointer}button:hover{border-color:var(--accent)}footer{margin-top:24px;color:var(--muted);font-size:.75rem}
.calibration-card{grid-column:1/-1}.calibration-help,.calibration-message{margin:10px 0 0;color:var(--muted);font-size:.82rem;line-height:1.45}.calibration-message{min-height:1.3em}.calibration-grid{margin-top:14px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.calibration-grid label{color:var(--muted);font-size:.75rem}.calibration-grid input{display:block;width:100%;margin-top:5px;border:1px solid var(--border);border-radius:7px;background:var(--panel2);color:var(--text);padding:9px;font:inherit;font-variant-numeric:tabular-nums}.calibration-actions{margin-top:14px}@media(max-width:520px){.calibration-grid{grid-template-columns:1fr}}
</style>
</head>
<body>
<div class="container">
<header><h1>Battery Monitor</h1><div class="subtitle">INA228 · ESP32-C3 · Live telemetry</div></header>
<div class="grid">
<div class="card"><div class="metric-name">Voltage</div><div class="metric-value" id="voltage">--</div><div class="extrema"><div><span class="label">Minimum</span><span class="extrema-value" id="voltage-min">--</span></div><div><span class="label">Maximum</span><span class="extrema-value" id="voltage-max">--</span></div></div></div>
<div class="card"><div class="metric-name">Current</div><div class="metric-value" id="current">--</div><div class="extrema"><div><span class="label">Minimum</span><span class="extrema-value" id="current-min">--</span></div><div><span class="label">Maximum</span><span class="extrema-value" id="current-max">--</span></div></div></div>
<div class="card"><div class="metric-name">Power</div><div class="metric-value" id="power">--</div><div class="extrema"><div><span class="label">Minimum</span><span class="extrema-value" id="power-min">--</span></div><div><span class="label">Maximum</span><span class="extrema-value" id="power-max">--</span></div></div></div>
<div class="card energy-card"><div class="metric-name">Session energy</div><div class="energy-summary"><div><span class="label">Net charge</span><span class="energy-primary" id="net-ah">--</span></div><div><span class="label">Net energy</span><span class="energy-primary" id="net-wh">--</span></div></div><div class="energy-details"><div><span class="label">Discharged</span><span class="energy-value" id="discharged-ah">--</span><span class="energy-value" id="discharged-wh">--</span></div><div><span class="label">Charged</span><span class="energy-value" id="charged-ah">--</span><span class="energy-value" id="charged-wh">--</span></div></div></div>
<div class="card sensor-card"><div class="metric-name">Sensor details</div><div class="sensor-grid"><div><span class="label">INA228 temperature</span><span class="sensor-value" id="temperature">--</span><span class="sensor-range"><span id="temperature-min">--</span> min · <span id="temperature-max">--</span> max</span></div><div><span class="label">Shunt voltage</span><span class="sensor-value" id="shuntVoltage">--</span><span class="sensor-range"><span id="shuntVoltage-min">--</span> min · <span id="shuntVoltage-max">--</span> max</span></div></div><div class="sensor-config" id="measurement-config">INA228 configuration loading...</div></div>
<div class="card calibration-card"><div class="metric-name">Guided calibration</div><div class="calibration-help">At zero current, capture the shunt offset. With a stable known current applied, capture a reference sample and calculate gain. Saving replaces the active profile and resets min/max and Ah/Wh.</div><div class="calibration-grid"><label>Nominal shunt (mOhm)<input id="cal-resistance" type="number" step="0.001" min="0.05"></label><label>Zero offset (uV)<input id="cal-offset" type="number" step="0.01" readonly></label><label>Reference shunt sample (uV)<input id="cal-sample" type="number" step="0.01" readonly></label><label>Known reference current (A)<input id="cal-reference" type="number" step="0.001" placeholder="e.g. 5.000"></label><label>Current gain<input id="cal-gain" type="number" step="0.000001" min="0.5" max="1.5"></label></div><div class="actions calibration-actions"><button onclick="captureZero()">1. Capture zero</button><button onclick="captureReference()">2. Capture reference</button><button onclick="calculateGain()">3. Calculate gain</button><button onclick="saveCalibration()">Save calibration</button><button onclick="resetCalibration()">Restore default</button></div><div class="calibration-message" id="calibration-message">Calibration loading...</div></div>
</div>
<div class="status-panel">
<div class="status" id="sensor-status"><span class="dot"></span>INA228</div>
<div class="status" id="ble-status"><span class="dot"></span>BLE</div>
<div class="status" id="wifi-status"><span class="dot"></span>Wi-Fi AP</div>
<div class="status" id="i2c-status"><span class="dot"></span>I2C</div>
<div class="status" id="display-status"><span class="dot"></span>Display</div>
</div>
<div class="actions"><button onclick="resetExtrema()">Reset min / max</button><button onclick="resetSession()">Reset Ah / Wh</button><button id="display-toggle" onclick="toggleDisplay()">Turn display off</button></div>
<footer><span id="uptime">Uptime --</span> · <span id="clients">0 Wi-Fi clients</span> · <span id="reset-reason">Last reset: --</span></footer>
</div>
<script>
const num=v=>typeof v==='number'&&Number.isFinite(v);
const fmtV=v=>num(v)?v.toFixed(3)+' V':'--';
const fmtI=v=>!num(v)?'--':Math.abs(v)<1?(v*1000).toFixed(3)+' mA':v.toFixed(3)+' A';
const fmtP=v=>!num(v)?'--':Math.abs(v)<1?(v*1000).toFixed(3)+' mW':v.toFixed(2)+' W';
const fmtT=v=>num(v)?v.toFixed(1)+' °C':'--';
const fmtS=v=>num(v)?(v*1000).toFixed(4)+' mV':'--';
const fmtAh=v=>!num(v)?'--':Math.abs(v)<1?(v*1000).toFixed(3)+' mAh':v.toFixed(4)+' Ah';
const fmtWh=v=>!num(v)?'--':Math.abs(v)<1?(v*1000).toFixed(3)+' mWh':v.toFixed(4)+' Wh';
const fmtR=v=>num(v)?(v*1000).toFixed(3)+' mOhm':'--';
let latestTelemetry=null;let calibrationDirty=false;let refreshInFlight=false;let commandInFlight=false;let refreshTimer=0;let lastCalibrationSequence=0;const REFRESH_INTERVAL_MS=500;const CALIBRATION_MAX_SAMPLE_AGE_MS=1500;
function metric(name,data,fmt){document.getElementById(name).textContent=fmt(data.value);document.getElementById(name+'-min').textContent=fmt(data.min);document.getElementById(name+'-max').textContent=fmt(data.max)}
function energy(data){document.getElementById('net-ah').textContent=fmtAh(data.netAh);document.getElementById('net-wh').textContent=fmtWh(data.netWh);document.getElementById('discharged-ah').textContent=fmtAh(data.dischargedAh);document.getElementById('discharged-wh').textContent=fmtWh(data.dischargedWh);document.getElementById('charged-ah').textContent=fmtAh(data.chargedAh);document.getElementById('charged-wh').textContent=fmtWh(data.chargedWh)}
function measurement(data){const e=document.getElementById('measurement-config');if(!data||!data.calibration){e.textContent='Measurement configuration unavailable';return}const c=data.calibration;const state=data.ina228Configured?'INA228 configured':data.ina228ReadbackValid?'INA228 configuration mismatch':'INA228 readback unavailable';const range=data.ina228ReadbackValid?(data.wideShuntRange?'wide +/-163.84 mV':'narrow +/-40.96 mV'):'range unavailable';const timing=data.ina228ReadbackValid?(data.averages+'x average | '+data.conversionTimeUs+' us conversion'):'timing unavailable';const source=c.stored?'stored calibration':'default calibration';e.textContent=state+' | '+range+' | '+timing+' | '+fmtR(c.shuntResistanceOhms)+' | offset '+c.shuntOffsetMicrovolts.toFixed(2)+' uV | gain '+c.currentGain.toFixed(6)+' ('+source+')';document.getElementById('calibration-message').textContent='Active profile: '+data.status;if(!calibrationDirty){document.getElementById('cal-resistance').value=(c.shuntResistanceOhms*1000).toFixed(6);document.getElementById('cal-offset').value=c.shuntOffsetMicrovolts.toFixed(2);document.getElementById('cal-gain').value=c.currentGain.toFixed(6)}}
function calibrationMessage(text){document.getElementById('calibration-message').textContent=text}
function currentShuntMicrovolts(){const t=latestTelemetry;if(!t||!t.sensorOK||!t.measurement||!t.measurement.ina228Configured||!num(t.sampleAgeMs)||t.sampleAgeMs>CALIBRATION_MAX_SAMPLE_AGE_MS||!num(t.shuntVoltage.value)){calibrationMessage('Wait for a fresh, healthy INA228 sample before capturing.');return null}if(t.sampleSequence===lastCalibrationSequence){calibrationMessage('Wait for the next telemetry sample before capturing again.');return null}lastCalibrationSequence=t.sampleSequence;return t.shuntVoltage.value*1e6}
function captureZero(){const value=currentShuntMicrovolts();if(value===null)return;document.getElementById('cal-offset').value=value.toFixed(2);calibrationDirty=true;calibrationMessage('Zero offset captured. Confirm there is no current before continuing.')}
function captureReference(){const value=currentShuntMicrovolts();if(value===null)return;document.getElementById('cal-sample').value=value.toFixed(2);calibrationDirty=true;calibrationMessage('Reference sample captured. Enter the trusted current, then calculate gain.')}
function calculateGain(){const r=Number(document.getElementById('cal-resistance').value)*1e-3;const offset=Number(document.getElementById('cal-offset').value)*1e-6;const sample=Number(document.getElementById('cal-sample').value)*1e-6;const reference=Number(document.getElementById('cal-reference').value);const observed=(sample-offset)/r;if(!Number.isFinite(observed)||!Number.isFinite(reference)||Math.abs(observed)<1e-9||Math.abs(reference)<1e-9||Math.sign(observed)!==Math.sign(reference)){calibrationMessage('Use a non-zero reference with the same current direction as the captured sample.');return}const gain=reference/observed;if(gain<0.5||gain>1.5){calibrationMessage('Calculated gain is outside the permitted 0.5 to 1.5 range. Check wiring and reference current.');return}document.getElementById('cal-gain').value=gain.toFixed(6);calibrationDirty=true;calibrationMessage('Gain calculated. Review all values, then save calibration.')}
async function postApi(path){if(commandInFlight)return false;commandInFlight=true;try{const response=await fetch(path,{method:'POST',cache:'no-store'});return response.ok}catch(e){return false}finally{commandInFlight=false}}
async function saveCalibration(){const r=Number(document.getElementById('cal-resistance').value)*1e-3;const offset=Number(document.getElementById('cal-offset').value)*1e-6;const gain=Number(document.getElementById('cal-gain').value);if(!Number.isFinite(r)||!Number.isFinite(offset)||!Number.isFinite(gain)){calibrationMessage('Enter valid calibration values before saving.');return}const q=new URLSearchParams({resistance:String(r),offset:String(offset),gain:String(gain)});if(!await postApi('/api/calibration/save?'+q)){calibrationMessage('Calibration was not accepted. Wait for any pending command, then check the values.');return}calibrationDirty=false;calibrationMessage('Saving calibration...');scheduleRefresh(150)}
async function resetCalibration(){if(!confirm('Restore the compile-time default calibration? This resets min/max and Ah/Wh.'))return;if(!await postApi('/api/calibration/reset')){calibrationMessage('Unable to restore the default calibration.');return}calibrationDirty=false;calibrationMessage('Restoring default calibration...');scheduleRefresh(150)}
function status(id,ok,text){const e=document.getElementById(id);e.classList.remove('good','bad');e.classList.add(ok?'good':'bad');e.innerHTML='<span class="dot"></span>'+text}
function uptime(s){s=Math.floor(s);const d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60);return d?d+'d '+h+'h':h?h+'h '+m+'m':m+'m'}
function scheduleRefresh(delay=REFRESH_INTERVAL_MS){clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,delay)}
async function refresh(){if(refreshInFlight)return;refreshInFlight=true;try{const r=await fetch('/api/telemetry',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();latestTelemetry=d;const fresh=num(d.sampleAgeMs)&&d.sampleAgeMs<=CALIBRATION_MAX_SAMPLE_AGE_MS;const healthy=d.sensorOK&&fresh;metric('voltage',d.voltage,fmtV);metric('current',d.current,fmtI);metric('power',d.power,fmtP);metric('temperature',d.temperature,fmtT);metric('shuntVoltage',d.shuntVoltage,fmtS);energy(d.energy);measurement(d.measurement);status('sensor-status',healthy,healthy?'INA228 OK':fresh?'INA228 error':'Telemetry stale');status('ble-status',d.bleConnected||d.bleAdvertising,d.bleConnected?'BLE connected':d.bleAdvertising?'BLE advertising':'BLE unavailable');status('wifi-status',d.accessPointReady,d.accessPointReady?'Wi-Fi AP ready':'Wi-Fi AP restarting');status('i2c-status',d.sensorOK,'Current sample: '+(d.sensorOK?'complete':'incomplete')+'; total incomplete: '+d.failedSamples);status('display-status',d.displayOn,d.displayOn?'Display on':'Display off');document.getElementById('display-toggle').textContent=d.displayOn?'Turn display off':'Turn display on';document.getElementById('uptime').textContent='Uptime '+uptime(d.uptimeSeconds);document.getElementById('clients').textContent=d.wifiClients+(d.wifiClients===1?' Wi-Fi client':' Wi-Fi clients');document.getElementById('reset-reason').textContent='Last reset: '+d.resetReason}catch(e){latestTelemetry=null;status('sensor-status',false,'Connection lost')}finally{refreshInFlight=false;scheduleRefresh()}}
async function resetExtrema(){if(await postApi('/api/reset-extrema'))scheduleRefresh(100)}
async function resetSession(){if(await postApi('/api/reset-session'))scheduleRefresh(100)}
async function toggleDisplay(){if(await postApi('/api/toggle-display'))scheduleRefresh(100)}
for(const id of ['cal-resistance','cal-reference','cal-gain'])document.getElementById(id).addEventListener('input',()=>{calibrationDirty=true});
refresh();
</script>
</body>
</html>
)HTML";
